/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as FirewallRouteImport } from './routes/firewall'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeersIdRouteImport } from './routes/peers.$id'
import { Route as ApiStatsIndexRouteImport } from './routes/api/stats/index'
import { Route as ApiPeersIndexRouteImport } from './routes/api/peers/index'
import { Route as ApiStatsPeerIdRouteImport } from './routes/api/stats/$peerId'
import { Route as ApiServerStopRouteImport } from './routes/api/server/stop'
import { Route as ApiServerStatusRouteImport } from './routes/api/server/status'
import { Route as ApiServerStartRouteImport } from './routes/api/server/start'
import { Route as ApiServerSshKeyRouteImport } from './routes/api/server/ssh-key'
import { Route as ApiServerRestartRouteImport } from './routes/api/server/restart'
import { Route as ApiServerPublicIpRouteImport } from './routes/api/server/public-ip'
import { Route as ApiServerKeysRouteImport } from './routes/api/server/keys'
import { Route as ApiServerFirewallRouteImport } from './routes/api/server/firewall'
import { Route as ApiServerConfigRouteImport } from './routes/api/server/config'
import { Route as ApiServerCheckRouteImport } from './routes/api/server/check'
import { Route as ApiPeersIdRouteImport } from './routes/api/peers/$id'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthPasswordRouteImport } from './routes/api/auth/password'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiPeersIdToggleRouteImport } from './routes/api/peers/$id.toggle'
import { Route as ApiPeersIdSystemInfoRouteImport } from './routes/api/peers/$id.system-info'
import { Route as ApiPeersIdSshExecRouteImport } from './routes/api/peers/$id.ssh-exec'
import { Route as ApiPeersIdSetupScriptRouteImport } from './routes/api/peers/$id.setup-script'
import { Route as ApiPeersIdQrcodeRouteImport } from './routes/api/peers/$id.qrcode'
import { Route as ApiPeersIdConfigRouteImport } from './routes/api/peers/$id.config'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallRoute = FirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersIdRoute = PeersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeersRoute,
} as any)
const ApiStatsIndexRoute = ApiStatsIndexRouteImport.update({
  id: '/api/stats/',
  path: '/api/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeersIndexRoute = ApiPeersIndexRouteImport.update({
  id: '/api/peers/',
  path: '/api/peers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsPeerIdRoute = ApiStatsPeerIdRouteImport.update({
  id: '/api/stats/$peerId',
  path: '/api/stats/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerStopRoute = ApiServerStopRouteImport.update({
  id: '/api/server/stop',
  path: '/api/server/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerStatusRoute = ApiServerStatusRouteImport.update({
  id: '/api/server/status',
  path: '/api/server/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerStartRoute = ApiServerStartRouteImport.update({
  id: '/api/server/start',
  path: '/api/server/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerSshKeyRoute = ApiServerSshKeyRouteImport.update({
  id: '/api/server/ssh-key',
  path: '/api/server/ssh-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerRestartRoute = ApiServerRestartRouteImport.update({
  id: '/api/server/restart',
  path: '/api/server/restart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerPublicIpRoute = ApiServerPublicIpRouteImport.update({
  id: '/api/server/public-ip',
  path: '/api/server/public-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerKeysRoute = ApiServerKeysRouteImport.update({
  id: '/api/server/keys',
  path: '/api/server/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerFirewallRoute = ApiServerFirewallRouteImport.update({
  id: '/api/server/firewall',
  path: '/api/server/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerConfigRoute = ApiServerConfigRouteImport.update({
  id: '/api/server/config',
  path: '/api/server/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerCheckRoute = ApiServerCheckRouteImport.update({
  id: '/api/server/check',
  path: '/api/server/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeersIdRoute = ApiPeersIdRouteImport.update({
  id: '/api/peers/$id',
  path: '/api/peers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/api/auth/password',
  path: '/api/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeersIdToggleRoute = ApiPeersIdToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiPeersIdRoute,
} as any)
const ApiPeersIdSystemInfoRoute = ApiPeersIdSystemInfoRouteImport.update({
  id: '/system-info',
  path: '/system-info',
  getParentRoute: () => ApiPeersIdRoute,
} as any)
const ApiPeersIdSshExecRoute = ApiPeersIdSshExecRouteImport.update({
  id: '/ssh-exec',
  path: '/ssh-exec',
  getParentRoute: () => ApiPeersIdRoute,
} as any)
const ApiPeersIdSetupScriptRoute = ApiPeersIdSetupScriptRouteImport.update({
  id: '/setup-script',
  path: '/setup-script',
  getParentRoute: () => ApiPeersIdRoute,
} as any)
const ApiPeersIdQrcodeRoute = ApiPeersIdQrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => ApiPeersIdRoute,
} as any)
const ApiPeersIdConfigRoute = ApiPeersIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApiPeersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firewall': typeof FirewallRoute
  '/peers': typeof PeersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/peers/$id': typeof PeersIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/peers/$id': typeof ApiPeersIdRouteWithChildren
  '/api/server/check': typeof ApiServerCheckRoute
  '/api/server/config': typeof ApiServerConfigRoute
  '/api/server/firewall': typeof ApiServerFirewallRoute
  '/api/server/keys': typeof ApiServerKeysRoute
  '/api/server/public-ip': typeof ApiServerPublicIpRoute
  '/api/server/restart': typeof ApiServerRestartRoute
  '/api/server/ssh-key': typeof ApiServerSshKeyRoute
  '/api/server/start': typeof ApiServerStartRoute
  '/api/server/status': typeof ApiServerStatusRoute
  '/api/server/stop': typeof ApiServerStopRoute
  '/api/stats/$peerId': typeof ApiStatsPeerIdRoute
  '/api/peers/': typeof ApiPeersIndexRoute
  '/api/stats/': typeof ApiStatsIndexRoute
  '/api/peers/$id/config': typeof ApiPeersIdConfigRoute
  '/api/peers/$id/qrcode': typeof ApiPeersIdQrcodeRoute
  '/api/peers/$id/setup-script': typeof ApiPeersIdSetupScriptRoute
  '/api/peers/$id/ssh-exec': typeof ApiPeersIdSshExecRoute
  '/api/peers/$id/system-info': typeof ApiPeersIdSystemInfoRoute
  '/api/peers/$id/toggle': typeof ApiPeersIdToggleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firewall': typeof FirewallRoute
  '/peers': typeof PeersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/peers/$id': typeof PeersIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/peers/$id': typeof ApiPeersIdRouteWithChildren
  '/api/server/check': typeof ApiServerCheckRoute
  '/api/server/config': typeof ApiServerConfigRoute
  '/api/server/firewall': typeof ApiServerFirewallRoute
  '/api/server/keys': typeof ApiServerKeysRoute
  '/api/server/public-ip': typeof ApiServerPublicIpRoute
  '/api/server/restart': typeof ApiServerRestartRoute
  '/api/server/ssh-key': typeof ApiServerSshKeyRoute
  '/api/server/start': typeof ApiServerStartRoute
  '/api/server/status': typeof ApiServerStatusRoute
  '/api/server/stop': typeof ApiServerStopRoute
  '/api/stats/$peerId': typeof ApiStatsPeerIdRoute
  '/api/peers': typeof ApiPeersIndexRoute
  '/api/stats': typeof ApiStatsIndexRoute
  '/api/peers/$id/config': typeof ApiPeersIdConfigRoute
  '/api/peers/$id/qrcode': typeof ApiPeersIdQrcodeRoute
  '/api/peers/$id/setup-script': typeof ApiPeersIdSetupScriptRoute
  '/api/peers/$id/ssh-exec': typeof ApiPeersIdSshExecRoute
  '/api/peers/$id/system-info': typeof ApiPeersIdSystemInfoRoute
  '/api/peers/$id/toggle': typeof ApiPeersIdToggleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/firewall': typeof FirewallRoute
  '/peers': typeof PeersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/peers/$id': typeof PeersIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/peers/$id': typeof ApiPeersIdRouteWithChildren
  '/api/server/check': typeof ApiServerCheckRoute
  '/api/server/config': typeof ApiServerConfigRoute
  '/api/server/firewall': typeof ApiServerFirewallRoute
  '/api/server/keys': typeof ApiServerKeysRoute
  '/api/server/public-ip': typeof ApiServerPublicIpRoute
  '/api/server/restart': typeof ApiServerRestartRoute
  '/api/server/ssh-key': typeof ApiServerSshKeyRoute
  '/api/server/start': typeof ApiServerStartRoute
  '/api/server/status': typeof ApiServerStatusRoute
  '/api/server/stop': typeof ApiServerStopRoute
  '/api/stats/$peerId': typeof ApiStatsPeerIdRoute
  '/api/peers/': typeof ApiPeersIndexRoute
  '/api/stats/': typeof ApiStatsIndexRoute
  '/api/peers/$id/config': typeof ApiPeersIdConfigRoute
  '/api/peers/$id/qrcode': typeof ApiPeersIdQrcodeRoute
  '/api/peers/$id/setup-script': typeof ApiPeersIdSetupScriptRoute
  '/api/peers/$id/ssh-exec': typeof ApiPeersIdSshExecRoute
  '/api/peers/$id/system-info': typeof ApiPeersIdSystemInfoRoute
  '/api/peers/$id/toggle': typeof ApiPeersIdToggleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/firewall'
    | '/peers'
    | '/settings'
    | '/peers/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/peers/$id'
    | '/api/server/check'
    | '/api/server/config'
    | '/api/server/firewall'
    | '/api/server/keys'
    | '/api/server/public-ip'
    | '/api/server/restart'
    | '/api/server/ssh-key'
    | '/api/server/start'
    | '/api/server/status'
    | '/api/server/stop'
    | '/api/stats/$peerId'
    | '/api/peers/'
    | '/api/stats/'
    | '/api/peers/$id/config'
    | '/api/peers/$id/qrcode'
    | '/api/peers/$id/setup-script'
    | '/api/peers/$id/ssh-exec'
    | '/api/peers/$id/system-info'
    | '/api/peers/$id/toggle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firewall'
    | '/peers'
    | '/settings'
    | '/peers/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/peers/$id'
    | '/api/server/check'
    | '/api/server/config'
    | '/api/server/firewall'
    | '/api/server/keys'
    | '/api/server/public-ip'
    | '/api/server/restart'
    | '/api/server/ssh-key'
    | '/api/server/start'
    | '/api/server/status'
    | '/api/server/stop'
    | '/api/stats/$peerId'
    | '/api/peers'
    | '/api/stats'
    | '/api/peers/$id/config'
    | '/api/peers/$id/qrcode'
    | '/api/peers/$id/setup-script'
    | '/api/peers/$id/ssh-exec'
    | '/api/peers/$id/system-info'
    | '/api/peers/$id/toggle'
  id:
    | '__root__'
    | '/'
    | '/firewall'
    | '/peers'
    | '/settings'
    | '/peers/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/peers/$id'
    | '/api/server/check'
    | '/api/server/config'
    | '/api/server/firewall'
    | '/api/server/keys'
    | '/api/server/public-ip'
    | '/api/server/restart'
    | '/api/server/ssh-key'
    | '/api/server/start'
    | '/api/server/status'
    | '/api/server/stop'
    | '/api/stats/$peerId'
    | '/api/peers/'
    | '/api/stats/'
    | '/api/peers/$id/config'
    | '/api/peers/$id/qrcode'
    | '/api/peers/$id/setup-script'
    | '/api/peers/$id/ssh-exec'
    | '/api/peers/$id/system-info'
    | '/api/peers/$id/toggle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirewallRoute: typeof FirewallRoute
  PeersRoute: typeof PeersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiPeersIdRoute: typeof ApiPeersIdRouteWithChildren
  ApiServerCheckRoute: typeof ApiServerCheckRoute
  ApiServerConfigRoute: typeof ApiServerConfigRoute
  ApiServerFirewallRoute: typeof ApiServerFirewallRoute
  ApiServerKeysRoute: typeof ApiServerKeysRoute
  ApiServerPublicIpRoute: typeof ApiServerPublicIpRoute
  ApiServerRestartRoute: typeof ApiServerRestartRoute
  ApiServerSshKeyRoute: typeof ApiServerSshKeyRoute
  ApiServerStartRoute: typeof ApiServerStartRoute
  ApiServerStatusRoute: typeof ApiServerStatusRoute
  ApiServerStopRoute: typeof ApiServerStopRoute
  ApiStatsPeerIdRoute: typeof ApiStatsPeerIdRoute
  ApiPeersIndexRoute: typeof ApiPeersIndexRoute
  ApiStatsIndexRoute: typeof ApiStatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewall': {
      id: '/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof FirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers/$id': {
      id: '/peers/$id'
      path: '/$id'
      fullPath: '/peers/$id'
      preLoaderRoute: typeof PeersIdRouteImport
      parentRoute: typeof PeersRoute
    }
    '/api/stats/': {
      id: '/api/stats/'
      path: '/api/stats'
      fullPath: '/api/stats/'
      preLoaderRoute: typeof ApiStatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peers/': {
      id: '/api/peers/'
      path: '/api/peers'
      fullPath: '/api/peers/'
      preLoaderRoute: typeof ApiPeersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/$peerId': {
      id: '/api/stats/$peerId'
      path: '/api/stats/$peerId'
      fullPath: '/api/stats/$peerId'
      preLoaderRoute: typeof ApiStatsPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/stop': {
      id: '/api/server/stop'
      path: '/api/server/stop'
      fullPath: '/api/server/stop'
      preLoaderRoute: typeof ApiServerStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/status': {
      id: '/api/server/status'
      path: '/api/server/status'
      fullPath: '/api/server/status'
      preLoaderRoute: typeof ApiServerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/start': {
      id: '/api/server/start'
      path: '/api/server/start'
      fullPath: '/api/server/start'
      preLoaderRoute: typeof ApiServerStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/ssh-key': {
      id: '/api/server/ssh-key'
      path: '/api/server/ssh-key'
      fullPath: '/api/server/ssh-key'
      preLoaderRoute: typeof ApiServerSshKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/restart': {
      id: '/api/server/restart'
      path: '/api/server/restart'
      fullPath: '/api/server/restart'
      preLoaderRoute: typeof ApiServerRestartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/public-ip': {
      id: '/api/server/public-ip'
      path: '/api/server/public-ip'
      fullPath: '/api/server/public-ip'
      preLoaderRoute: typeof ApiServerPublicIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/keys': {
      id: '/api/server/keys'
      path: '/api/server/keys'
      fullPath: '/api/server/keys'
      preLoaderRoute: typeof ApiServerKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/firewall': {
      id: '/api/server/firewall'
      path: '/api/server/firewall'
      fullPath: '/api/server/firewall'
      preLoaderRoute: typeof ApiServerFirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/config': {
      id: '/api/server/config'
      path: '/api/server/config'
      fullPath: '/api/server/config'
      preLoaderRoute: typeof ApiServerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/check': {
      id: '/api/server/check'
      path: '/api/server/check'
      fullPath: '/api/server/check'
      preLoaderRoute: typeof ApiServerCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peers/$id': {
      id: '/api/peers/$id'
      path: '/api/peers/$id'
      fullPath: '/api/peers/$id'
      preLoaderRoute: typeof ApiPeersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/api/auth/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peers/$id/toggle': {
      id: '/api/peers/$id/toggle'
      path: '/toggle'
      fullPath: '/api/peers/$id/toggle'
      preLoaderRoute: typeof ApiPeersIdToggleRouteImport
      parentRoute: typeof ApiPeersIdRoute
    }
    '/api/peers/$id/system-info': {
      id: '/api/peers/$id/system-info'
      path: '/system-info'
      fullPath: '/api/peers/$id/system-info'
      preLoaderRoute: typeof ApiPeersIdSystemInfoRouteImport
      parentRoute: typeof ApiPeersIdRoute
    }
    '/api/peers/$id/ssh-exec': {
      id: '/api/peers/$id/ssh-exec'
      path: '/ssh-exec'
      fullPath: '/api/peers/$id/ssh-exec'
      preLoaderRoute: typeof ApiPeersIdSshExecRouteImport
      parentRoute: typeof ApiPeersIdRoute
    }
    '/api/peers/$id/setup-script': {
      id: '/api/peers/$id/setup-script'
      path: '/setup-script'
      fullPath: '/api/peers/$id/setup-script'
      preLoaderRoute: typeof ApiPeersIdSetupScriptRouteImport
      parentRoute: typeof ApiPeersIdRoute
    }
    '/api/peers/$id/qrcode': {
      id: '/api/peers/$id/qrcode'
      path: '/qrcode'
      fullPath: '/api/peers/$id/qrcode'
      preLoaderRoute: typeof ApiPeersIdQrcodeRouteImport
      parentRoute: typeof ApiPeersIdRoute
    }
    '/api/peers/$id/config': {
      id: '/api/peers/$id/config'
      path: '/config'
      fullPath: '/api/peers/$id/config'
      preLoaderRoute: typeof ApiPeersIdConfigRouteImport
      parentRoute: typeof ApiPeersIdRoute
    }
  }
}

interface PeersRouteChildren {
  PeersIdRoute: typeof PeersIdRoute
}

const PeersRouteChildren: PeersRouteChildren = {
  PeersIdRoute: PeersIdRoute,
}

const PeersRouteWithChildren = PeersRoute._addFileChildren(PeersRouteChildren)

interface ApiPeersIdRouteChildren {
  ApiPeersIdConfigRoute: typeof ApiPeersIdConfigRoute
  ApiPeersIdQrcodeRoute: typeof ApiPeersIdQrcodeRoute
  ApiPeersIdSetupScriptRoute: typeof ApiPeersIdSetupScriptRoute
  ApiPeersIdSshExecRoute: typeof ApiPeersIdSshExecRoute
  ApiPeersIdSystemInfoRoute: typeof ApiPeersIdSystemInfoRoute
  ApiPeersIdToggleRoute: typeof ApiPeersIdToggleRoute
}

const ApiPeersIdRouteChildren: ApiPeersIdRouteChildren = {
  ApiPeersIdConfigRoute: ApiPeersIdConfigRoute,
  ApiPeersIdQrcodeRoute: ApiPeersIdQrcodeRoute,
  ApiPeersIdSetupScriptRoute: ApiPeersIdSetupScriptRoute,
  ApiPeersIdSshExecRoute: ApiPeersIdSshExecRoute,
  ApiPeersIdSystemInfoRoute: ApiPeersIdSystemInfoRoute,
  ApiPeersIdToggleRoute: ApiPeersIdToggleRoute,
}

const ApiPeersIdRouteWithChildren = ApiPeersIdRoute._addFileChildren(
  ApiPeersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirewallRoute: FirewallRoute,
  PeersRoute: PeersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiPeersIdRoute: ApiPeersIdRouteWithChildren,
  ApiServerCheckRoute: ApiServerCheckRoute,
  ApiServerConfigRoute: ApiServerConfigRoute,
  ApiServerFirewallRoute: ApiServerFirewallRoute,
  ApiServerKeysRoute: ApiServerKeysRoute,
  ApiServerPublicIpRoute: ApiServerPublicIpRoute,
  ApiServerRestartRoute: ApiServerRestartRoute,
  ApiServerSshKeyRoute: ApiServerSshKeyRoute,
  ApiServerStartRoute: ApiServerStartRoute,
  ApiServerStatusRoute: ApiServerStatusRoute,
  ApiServerStopRoute: ApiServerStopRoute,
  ApiStatsPeerIdRoute: ApiStatsPeerIdRoute,
  ApiPeersIndexRoute: ApiPeersIndexRoute,
  ApiStatsIndexRoute: ApiStatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
